
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           23547
     no. of nonzeroes in lower triangle of a =          871503
     no. of nonzeroes in the factor l        =         4485462
     ratio of nonzeroes in factor (min/max)  =          0.8963
     number of super nodes                   =             878
     maximum order of a front matrix         =             513
     maximum size of a front matrix          =          131841
     maximum size of a front trapezoid       =          108711
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.0065D+09
     no. of floating point ops for solve     =      1.6452D+07
     ratio of flops for factor (min/max)     =          0.8161
     ratio of allocated memory (max/min)     =          1.1018
     number of positive pivots               =           23547
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.002257
     time (cpu & wall) for ordering          =        0.031250        0.038247
     time (cpu & wall) for other matrix prep =        0.015625        0.005202
     time (cpu & wall) for value input       =        0.000000        0.005910
     time (cpu & wall) for matrix distrib.   =        0.031250        0.031915
     time (cpu & wall) for numeric factor    =        0.046875        0.045508
     computational rate (gflops) for factor  =       21.471645       22.116479
     time (cpu & wall) for numeric solve     =        0.015625        0.004723
     computational rate (gflops) for solve   =        1.052908        3.483166
     effective I/O rate (GB/sec) for solve   =        3.922699       12.976833

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         52167.        0. MB
                95-   1         65536.        0. MB         62726.        0. MB
                95-   2         65536.        0. MB         61268.        0. MB
                95-   3         65536.        0. MB         58587.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        262144.        2. MB        234748.        2. MB


  Solver Memory allocated on core    0       =       19.963 MB
  Solver Memory allocated on core    1       =       19.252 MB
  Solver Memory allocated on core    2       =       20.690 MB
  Solver Memory allocated on core    3       =       18.778 MB
  Total Solver Memory allocated by all cores =       78.682 MB

